import { jsPDF } from 'jspdf';
import { formatINR, formatDate } from './validate';

export function generateQuotationPDF(quotation, customer, user) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 50;

  // Header band
  doc.setFillColor(31, 102, 245);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('QuotaAI', margin, 20);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI Quotation Generator', pageWidth - margin, 20, { align: 'right' });

  y = 50;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('QUOTATION', margin, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Quotation No: ${quotation.id.slice(-8).toUpperCase()}`, margin, y);
  doc.text(`Date: ${formatDate(quotation.createdAt)}`, pageWidth - margin, y, { align: 'right' });
  y += 16;

  // From / To
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', margin, y);
  doc.text('To:', pageWidth / 2, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(user?.companyName || 'Acme Manufacturing', margin, y);
  doc.text(customer?.name || '—', pageWidth / 2, y);
  y += 5;
  doc.text(user?.fullName || '', margin, y);
  doc.text(customer?.contactPerson || '', pageWidth / 2, y);
  y += 5;
  doc.text(user?.email || '', margin, y);
  doc.text(customer?.email || '', pageWidth / 2, y);
  y += 5;
  doc.text(user?.mobile || '', margin, y);
  doc.text(customer?.mobile || '', pageWidth / 2, y);

  y += 14;
  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y - 6, pageWidth - margin * 2, 10, 'F');
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Product', margin + 4, y);
  doc.text('Qty', pageWidth - margin - 120, y, { align: 'right' });
  doc.text('Unit Price', pageWidth - margin - 70, y, { align: 'right' });
  doc.text('Total', pageWidth - margin - 4, y, { align: 'right' });
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  quotation.lines.forEach((l) => {
    if (y > 260) { doc.addPage(); y = 40; }
    doc.text(l.name.slice(0, 40), margin + 4, y);
    doc.text(String(l.qty), pageWidth - margin - 120, y, { align: 'right' });
    doc.text(formatINR(l.sellingPrice), pageWidth - margin - 70, y, { align: 'right' });
    doc.text(formatINR(l.total), pageWidth - margin - 4, y, { align: 'right' });
    y += 8;
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(l.sku, margin + 4, y);
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    y += 6;
  });

  y += 6;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Subtotal', pageWidth - margin - 60, y);
  doc.text(formatINR(quotation.subtotal), pageWidth - margin - 4, y, { align: 'right' });
  y += 7;
  doc.text(`GST (${quotation.taxRate}%)`, pageWidth - margin - 60, y);
  doc.text(formatINR(quotation.tax), pageWidth - margin - 4, y, { align: 'right' });
  y += 10;

  doc.setFillColor(31, 102, 245);
  doc.rect(pageWidth - margin - 70, y - 6, 70, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Grand Total', pageWidth - margin - 66, y + 2);
  doc.text(formatINR(quotation.grandTotal), pageWidth - margin - 4, y + 2, { align: 'right' });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('This quotation is valid for 30 days from the date of issue.', margin, pageHeight - 30);
  doc.text('Generated by QuotaAI — AI Quotation Generator', margin, pageHeight - 22);

  doc.save(`Quotation_${quotation.id.slice(-8).toUpperCase()}.pdf`);
}
